@baseUrl = http://127.0.0.1:3000
@contentType = application/json

#Listar tasks
GET {{baseUrl}}/task HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{login.response.body.token}}
Origin: http://127.0.0.1:3000

###

#Recuperar tasks
GET {{baseUrl}}/task/1 HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{login.response.body.token}}
Origin: http://127.0.0.1:3000

###

#Criar task
POST {{baseUrl}}/task HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{login.response.body.token}}
Origin: http://127.0.0.1:3000

{
  "title": "Titulo da tarefa {{$timestamp}}",
  "description": "Descrição da tarefa",
  "finished": false
}

###

#Editar task
PUT {{baseUrl}}/task/2 HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{login.response.body.token}}
Origin: http://127.0.0.1:3000

{
  "title": "Titulo da tarefa alterado",
  "description": "Descrição da tarefa alterada",
	"finished" : true
}

###

#Delete Task
DELETE {{baseUrl}}/task/2 HTTP/1.1
Authorization: Bearer {{login.response.body.token}}
Origin: http://127.0.0.1:3000

###

#Registrar usuario
# @name login
POST {{baseUrl}}/register HTTP/1.1
Content-Type: {{contentType}}
Origin: http://127.0.0.1:3000

{
	"name": "Cristiano",
	"email": "admin@mail.com",
	"password": "123456"
}

###

#Logar usuario
# @name login
POST {{baseUrl}}/login HTTP/1.1
Content-Type: {{contentType}}
Origin: http://127.0.0.1:3000

{
	"email": "admin@mail.com",
	"password": "123456"
}